### PR TITLE
Update zh_CN.lang

### PR DESCRIPTION
**Pull request by DYColdWind**

### CODE REVIEW

**Comment by Morpheus1101** [comment]
I count 8 names out of the 13 Singularities

**Comment by DYColdWind** [comment]
Sorry, I do not really understand the meaning of 'I count 8 names out of the 13 Singularities'.
Can you explain in more detail?

**Comment by Morpheus1101** [comment]
There are 13 Singularities and looking in this file you have names for 8 of them

**Comment by covers1624** [comment]
Nope they are there just hidden by git as there is no changes to them.

**Comment by covers1624** [comment]
Looks good to me @DYColdWind Any more changes or is this ready to be merged?

**Comment by DYColdWind** [comment]
I think there should be no change until the next update.
@covers1624  Merge it

**Pull request merged**
